owner: chatwoot
repo: status

sites:
  - name: Chatwoot
    url: https://app.chatwoot.com
assignees:
  - vishnu-narayanan
  - sojan-official
status-website:
  cname: status.chatwoot.com
  logoUrl: https://chatwoot-public-assets.s3.amazonaws.com/logo/square.png
  name: Chatwoot Status
  introTitle: "This is the status page for Chatwoot."
  introMessage: This is the realtime status page for Chatwoot.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
